name: Deploy Documentation

on:
  # Trigger when documentation files are updated on master
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'README.md'
  # Manual trigger
  workflow_dispatch:

jobs:
  deploy-docs:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload documentation artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

      - name: Output deployment URL
        run: |
          echo "Documentation deployed successfully!"
          echo "Available at: ${{ steps.deployment.outputs.page_url }}"