name: CI/CD Pipeline

on:
  push:
    branches: [ master, devel ]
    paths:
      # Trigger on code changes
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'utils/**'
      - 'CMakeLists.txt'
      - '.github/workflows/**'
  pull_request:
    branches: [ master, devel ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'utils/**'
      - 'CMakeLists.txt'
      - '.github/workflows/**'

jobs:
  # Test and build the library
  test-build:
    name: Test and Build Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev

      - name: Build Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cd build
          make -j$(nproc)

      - name: Run tests
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=1 ctest --verbose